// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/shillingio/scheduling.go/models"
)

// NewSchedulerCreateServiceParams creates a new SchedulerCreateServiceParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSchedulerCreateServiceParams() *SchedulerCreateServiceParams {
	return &SchedulerCreateServiceParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSchedulerCreateServiceParamsWithTimeout creates a new SchedulerCreateServiceParams object
// with the ability to set a timeout on a request.
func NewSchedulerCreateServiceParamsWithTimeout(timeout time.Duration) *SchedulerCreateServiceParams {
	return &SchedulerCreateServiceParams{
		timeout: timeout,
	}
}

// NewSchedulerCreateServiceParamsWithContext creates a new SchedulerCreateServiceParams object
// with the ability to set a context for a request.
func NewSchedulerCreateServiceParamsWithContext(ctx context.Context) *SchedulerCreateServiceParams {
	return &SchedulerCreateServiceParams{
		Context: ctx,
	}
}

// NewSchedulerCreateServiceParamsWithHTTPClient creates a new SchedulerCreateServiceParams object
// with the ability to set a custom HTTPClient for a request.
func NewSchedulerCreateServiceParamsWithHTTPClient(client *http.Client) *SchedulerCreateServiceParams {
	return &SchedulerCreateServiceParams{
		HTTPClient: client,
	}
}

/* SchedulerCreateServiceParams contains all the parameters to send to the API endpoint
   for the scheduler create service operation.

   Typically these are written to a http.Request.
*/
type SchedulerCreateServiceParams struct {

	// Body.
	Body *models.SchedulingService

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the scheduler create service params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SchedulerCreateServiceParams) WithDefaults() *SchedulerCreateServiceParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the scheduler create service params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SchedulerCreateServiceParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the scheduler create service params
func (o *SchedulerCreateServiceParams) WithTimeout(timeout time.Duration) *SchedulerCreateServiceParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the scheduler create service params
func (o *SchedulerCreateServiceParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the scheduler create service params
func (o *SchedulerCreateServiceParams) WithContext(ctx context.Context) *SchedulerCreateServiceParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the scheduler create service params
func (o *SchedulerCreateServiceParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the scheduler create service params
func (o *SchedulerCreateServiceParams) WithHTTPClient(client *http.Client) *SchedulerCreateServiceParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the scheduler create service params
func (o *SchedulerCreateServiceParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the scheduler create service params
func (o *SchedulerCreateServiceParams) WithBody(body *models.SchedulingService) *SchedulerCreateServiceParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the scheduler create service params
func (o *SchedulerCreateServiceParams) SetBody(body *models.SchedulingService) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SchedulerCreateServiceParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
