// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/shillingio/scheduling.go/models"
)

// SchedulerActivateProviderReader is a Reader for the SchedulerActivateProvider structure.
type SchedulerActivateProviderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SchedulerActivateProviderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSchedulerActivateProviderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSchedulerActivateProviderDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSchedulerActivateProviderOK creates a SchedulerActivateProviderOK with default headers values
func NewSchedulerActivateProviderOK() *SchedulerActivateProviderOK {
	return &SchedulerActivateProviderOK{}
}

/* SchedulerActivateProviderOK describes a response with status code 200, with default header values.

A successful response.
*/
type SchedulerActivateProviderOK struct {
	Payload *models.SchedulerProviderResponse
}

func (o *SchedulerActivateProviderOK) Error() string {
	return fmt.Sprintf("[PUT /v1/providers/{id}/activate][%d] schedulerActivateProviderOK  %+v", 200, o.Payload)
}
func (o *SchedulerActivateProviderOK) GetPayload() *models.SchedulerProviderResponse {
	return o.Payload
}

func (o *SchedulerActivateProviderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SchedulerProviderResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSchedulerActivateProviderDefault creates a SchedulerActivateProviderDefault with default headers values
func NewSchedulerActivateProviderDefault(code int) *SchedulerActivateProviderDefault {
	return &SchedulerActivateProviderDefault{
		_statusCode: code,
	}
}

/* SchedulerActivateProviderDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SchedulerActivateProviderDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the scheduler activate provider default response
func (o *SchedulerActivateProviderDefault) Code() int {
	return o._statusCode
}

func (o *SchedulerActivateProviderDefault) Error() string {
	return fmt.Sprintf("[PUT /v1/providers/{id}/activate][%d] Scheduler_ActivateProvider default  %+v", o._statusCode, o.Payload)
}
func (o *SchedulerActivateProviderDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SchedulerActivateProviderDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*SchedulerActivateProviderBody scheduler activate provider body
// Example: {}
swagger:model SchedulerActivateProviderBody
*/
type SchedulerActivateProviderBody struct {

	// active
	Active bool `json:"active,omitempty"`

	// Available appointments for the provider
	Appointments map[string]models.SchedulingAppointment `json:"appointments,omitempty"`

	// created at
	CreatedAt string `json:"created_at,omitempty"`

	// created by
	CreatedBy string `json:"created_by,omitempty"`

	// gender
	Gender string `json:"gender,omitempty"`

	// given name
	GivenName string `json:"given_name,omitempty"`

	// org id
	OrgID string `json:"org_id,omitempty"`

	// prefix
	Prefix string `json:"prefix,omitempty"`

	// ref id
	RefID string `json:"ref_id,omitempty"`

	// role
	Role string `json:"role,omitempty"`

	// suffix
	Suffix string `json:"suffix,omitempty"`

	// surname
	Surname string `json:"surname,omitempty"`

	// timezone
	Timezone *models.SchedulingTimezone `json:"timezone,omitempty"`

	// updated at
	UpdatedAt string `json:"updated_at,omitempty"`

	// updated by
	UpdatedBy string `json:"updated_by,omitempty"`
}

// Validate validates this scheduler activate provider body
func (o *SchedulerActivateProviderBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAppointments(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateTimezone(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SchedulerActivateProviderBody) validateAppointments(formats strfmt.Registry) error {
	if swag.IsZero(o.Appointments) { // not required
		return nil
	}

	for k := range o.Appointments {

		if err := validate.Required("body"+"."+"appointments"+"."+k, "body", o.Appointments[k]); err != nil {
			return err
		}
		if val, ok := o.Appointments[k]; ok {
			if err := val.Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("body" + "." + "appointments" + "." + k)
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("body" + "." + "appointments" + "." + k)
				}
				return err
			}
		}

	}

	return nil
}

func (o *SchedulerActivateProviderBody) validateTimezone(formats strfmt.Registry) error {
	if swag.IsZero(o.Timezone) { // not required
		return nil
	}

	if o.Timezone != nil {
		if err := o.Timezone.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "timezone")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "timezone")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this scheduler activate provider body based on the context it is used
func (o *SchedulerActivateProviderBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateAppointments(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateTimezone(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SchedulerActivateProviderBody) contextValidateAppointments(ctx context.Context, formats strfmt.Registry) error {

	for k := range o.Appointments {

		if val, ok := o.Appointments[k]; ok {
			if err := val.ContextValidate(ctx, formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (o *SchedulerActivateProviderBody) contextValidateTimezone(ctx context.Context, formats strfmt.Registry) error {

	if o.Timezone != nil {
		if err := o.Timezone.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("body" + "." + "timezone")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("body" + "." + "timezone")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *SchedulerActivateProviderBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SchedulerActivateProviderBody) UnmarshalBinary(b []byte) error {
	var res SchedulerActivateProviderBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
