// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/shillingio/scheduling.go/models"
)

// SchedulerGetProviderServicesReader is a Reader for the SchedulerGetProviderServices structure.
type SchedulerGetProviderServicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SchedulerGetProviderServicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSchedulerGetProviderServicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSchedulerGetProviderServicesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSchedulerGetProviderServicesOK creates a SchedulerGetProviderServicesOK with default headers values
func NewSchedulerGetProviderServicesOK() *SchedulerGetProviderServicesOK {
	return &SchedulerGetProviderServicesOK{}
}

/* SchedulerGetProviderServicesOK describes a response with status code 200, with default header values.

A successful response.
*/
type SchedulerGetProviderServicesOK struct {
	Payload *models.SchedulerProviderServiceResponse
}

func (o *SchedulerGetProviderServicesOK) Error() string {
	return fmt.Sprintf("[GET /v1/providers/{provider_id}/services][%d] schedulerGetProviderServicesOK  %+v", 200, o.Payload)
}
func (o *SchedulerGetProviderServicesOK) GetPayload() *models.SchedulerProviderServiceResponse {
	return o.Payload
}

func (o *SchedulerGetProviderServicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SchedulerProviderServiceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSchedulerGetProviderServicesDefault creates a SchedulerGetProviderServicesDefault with default headers values
func NewSchedulerGetProviderServicesDefault(code int) *SchedulerGetProviderServicesDefault {
	return &SchedulerGetProviderServicesDefault{
		_statusCode: code,
	}
}

/* SchedulerGetProviderServicesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SchedulerGetProviderServicesDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the scheduler get provider services default response
func (o *SchedulerGetProviderServicesDefault) Code() int {
	return o._statusCode
}

func (o *SchedulerGetProviderServicesDefault) Error() string {
	return fmt.Sprintf("[GET /v1/providers/{provider_id}/services][%d] Scheduler_GetProviderServices default  %+v", o._statusCode, o.Payload)
}
func (o *SchedulerGetProviderServicesDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SchedulerGetProviderServicesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
