// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/shillingio/scheduling.go/models"
)

// SchedulerCreateSessionKeyReader is a Reader for the SchedulerCreateSessionKey structure.
type SchedulerCreateSessionKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SchedulerCreateSessionKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSchedulerCreateSessionKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSchedulerCreateSessionKeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSchedulerCreateSessionKeyOK creates a SchedulerCreateSessionKeyOK with default headers values
func NewSchedulerCreateSessionKeyOK() *SchedulerCreateSessionKeyOK {
	return &SchedulerCreateSessionKeyOK{}
}

/* SchedulerCreateSessionKeyOK describes a response with status code 200, with default header values.

A successful response.
*/
type SchedulerCreateSessionKeyOK struct {
	Payload *models.SchedulerSessionKeyResponse
}

func (o *SchedulerCreateSessionKeyOK) Error() string {
	return fmt.Sprintf("[POST /v1/sessions/keys][%d] schedulerCreateSessionKeyOK  %+v", 200, o.Payload)
}
func (o *SchedulerCreateSessionKeyOK) GetPayload() *models.SchedulerSessionKeyResponse {
	return o.Payload
}

func (o *SchedulerCreateSessionKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SchedulerSessionKeyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSchedulerCreateSessionKeyDefault creates a SchedulerCreateSessionKeyDefault with default headers values
func NewSchedulerCreateSessionKeyDefault(code int) *SchedulerCreateSessionKeyDefault {
	return &SchedulerCreateSessionKeyDefault{
		_statusCode: code,
	}
}

/* SchedulerCreateSessionKeyDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SchedulerCreateSessionKeyDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the scheduler create session key default response
func (o *SchedulerCreateSessionKeyDefault) Code() int {
	return o._statusCode
}

func (o *SchedulerCreateSessionKeyDefault) Error() string {
	return fmt.Sprintf("[POST /v1/sessions/keys][%d] Scheduler_CreateSessionKey default  %+v", o._statusCode, o.Payload)
}
func (o *SchedulerCreateSessionKeyDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SchedulerCreateSessionKeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
