// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/shillingio/scheduling.go/models"
)

// SchedulerGetZipcodeReader is a Reader for the SchedulerGetZipcode structure.
type SchedulerGetZipcodeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SchedulerGetZipcodeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSchedulerGetZipcodeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSchedulerGetZipcodeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSchedulerGetZipcodeOK creates a SchedulerGetZipcodeOK with default headers values
func NewSchedulerGetZipcodeOK() *SchedulerGetZipcodeOK {
	return &SchedulerGetZipcodeOK{}
}

/* SchedulerGetZipcodeOK describes a response with status code 200, with default header values.

A successful response.
*/
type SchedulerGetZipcodeOK struct {
	Payload *models.SchedulerZipcodeResponse
}

func (o *SchedulerGetZipcodeOK) Error() string {
	return fmt.Sprintf("[GET /v1/zipcodes/{zip}][%d] schedulerGetZipcodeOK  %+v", 200, o.Payload)
}
func (o *SchedulerGetZipcodeOK) GetPayload() *models.SchedulerZipcodeResponse {
	return o.Payload
}

func (o *SchedulerGetZipcodeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SchedulerZipcodeResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSchedulerGetZipcodeDefault creates a SchedulerGetZipcodeDefault with default headers values
func NewSchedulerGetZipcodeDefault(code int) *SchedulerGetZipcodeDefault {
	return &SchedulerGetZipcodeDefault{
		_statusCode: code,
	}
}

/* SchedulerGetZipcodeDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SchedulerGetZipcodeDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the scheduler get zipcode default response
func (o *SchedulerGetZipcodeDefault) Code() int {
	return o._statusCode
}

func (o *SchedulerGetZipcodeDefault) Error() string {
	return fmt.Sprintf("[GET /v1/zipcodes/{zip}][%d] Scheduler_GetZipcode default  %+v", o._statusCode, o.Payload)
}
func (o *SchedulerGetZipcodeDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SchedulerGetZipcodeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
