// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/shillingio/scheduling.go/models"
)

// SchedulerGetServicesReader is a Reader for the SchedulerGetServices structure.
type SchedulerGetServicesReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SchedulerGetServicesReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSchedulerGetServicesOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSchedulerGetServicesDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSchedulerGetServicesOK creates a SchedulerGetServicesOK with default headers values
func NewSchedulerGetServicesOK() *SchedulerGetServicesOK {
	return &SchedulerGetServicesOK{}
}

/* SchedulerGetServicesOK describes a response with status code 200, with default header values.

A successful response.
*/
type SchedulerGetServicesOK struct {
	Payload *models.SchedulerServiceResponse
}

func (o *SchedulerGetServicesOK) Error() string {
	return fmt.Sprintf("[GET /v1/services][%d] schedulerGetServicesOK  %+v", 200, o.Payload)
}
func (o *SchedulerGetServicesOK) GetPayload() *models.SchedulerServiceResponse {
	return o.Payload
}

func (o *SchedulerGetServicesOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SchedulerServiceResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSchedulerGetServicesDefault creates a SchedulerGetServicesDefault with default headers values
func NewSchedulerGetServicesDefault(code int) *SchedulerGetServicesDefault {
	return &SchedulerGetServicesDefault{
		_statusCode: code,
	}
}

/* SchedulerGetServicesDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SchedulerGetServicesDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the scheduler get services default response
func (o *SchedulerGetServicesDefault) Code() int {
	return o._statusCode
}

func (o *SchedulerGetServicesDefault) Error() string {
	return fmt.Sprintf("[GET /v1/services][%d] Scheduler_GetServices default  %+v", o._statusCode, o.Payload)
}
func (o *SchedulerGetServicesDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SchedulerGetServicesDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
