// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/shillingio/scheduling.go/models"
)

// SchedulerGetProvidersReader is a Reader for the SchedulerGetProviders structure.
type SchedulerGetProvidersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SchedulerGetProvidersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSchedulerGetProvidersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSchedulerGetProvidersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSchedulerGetProvidersOK creates a SchedulerGetProvidersOK with default headers values
func NewSchedulerGetProvidersOK() *SchedulerGetProvidersOK {
	return &SchedulerGetProvidersOK{}
}

/* SchedulerGetProvidersOK describes a response with status code 200, with default header values.

A successful response.
*/
type SchedulerGetProvidersOK struct {
	Payload *models.SchedulerProviderResponse
}

func (o *SchedulerGetProvidersOK) Error() string {
	return fmt.Sprintf("[GET /v1/providers][%d] schedulerGetProvidersOK  %+v", 200, o.Payload)
}
func (o *SchedulerGetProvidersOK) GetPayload() *models.SchedulerProviderResponse {
	return o.Payload
}

func (o *SchedulerGetProvidersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SchedulerProviderResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSchedulerGetProvidersDefault creates a SchedulerGetProvidersDefault with default headers values
func NewSchedulerGetProvidersDefault(code int) *SchedulerGetProvidersDefault {
	return &SchedulerGetProvidersDefault{
		_statusCode: code,
	}
}

/* SchedulerGetProvidersDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SchedulerGetProvidersDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the scheduler get providers default response
func (o *SchedulerGetProvidersDefault) Code() int {
	return o._statusCode
}

func (o *SchedulerGetProvidersDefault) Error() string {
	return fmt.Sprintf("[GET /v1/providers][%d] Scheduler_GetProviders default  %+v", o._statusCode, o.Payload)
}
func (o *SchedulerGetProvidersDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SchedulerGetProvidersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
