// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/shillingio/scheduling.go/models"
)

// SchedulerGetSessionKeyReader is a Reader for the SchedulerGetSessionKey structure.
type SchedulerGetSessionKeyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SchedulerGetSessionKeyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSchedulerGetSessionKeyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSchedulerGetSessionKeyDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSchedulerGetSessionKeyOK creates a SchedulerGetSessionKeyOK with default headers values
func NewSchedulerGetSessionKeyOK() *SchedulerGetSessionKeyOK {
	return &SchedulerGetSessionKeyOK{}
}

/* SchedulerGetSessionKeyOK describes a response with status code 200, with default header values.

A successful response.
*/
type SchedulerGetSessionKeyOK struct {
	Payload *models.SchedulerSessionKeyResponse
}

func (o *SchedulerGetSessionKeyOK) Error() string {
	return fmt.Sprintf("[GET /v1/sessions/keys/{key}][%d] schedulerGetSessionKeyOK  %+v", 200, o.Payload)
}
func (o *SchedulerGetSessionKeyOK) GetPayload() *models.SchedulerSessionKeyResponse {
	return o.Payload
}

func (o *SchedulerGetSessionKeyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SchedulerSessionKeyResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSchedulerGetSessionKeyDefault creates a SchedulerGetSessionKeyDefault with default headers values
func NewSchedulerGetSessionKeyDefault(code int) *SchedulerGetSessionKeyDefault {
	return &SchedulerGetSessionKeyDefault{
		_statusCode: code,
	}
}

/* SchedulerGetSessionKeyDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SchedulerGetSessionKeyDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the scheduler get session key default response
func (o *SchedulerGetSessionKeyDefault) Code() int {
	return o._statusCode
}

func (o *SchedulerGetSessionKeyDefault) Error() string {
	return fmt.Sprintf("[GET /v1/sessions/keys/{key}][%d] Scheduler_GetSessionKey default  %+v", o._statusCode, o.Payload)
}
func (o *SchedulerGetSessionKeyDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SchedulerGetSessionKeyDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
