// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/shillingio/scheduling.go/models"
)

// NewSchedulerCreateSessionKeyParams creates a new SchedulerCreateSessionKeyParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSchedulerCreateSessionKeyParams() *SchedulerCreateSessionKeyParams {
	return &SchedulerCreateSessionKeyParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSchedulerCreateSessionKeyParamsWithTimeout creates a new SchedulerCreateSessionKeyParams object
// with the ability to set a timeout on a request.
func NewSchedulerCreateSessionKeyParamsWithTimeout(timeout time.Duration) *SchedulerCreateSessionKeyParams {
	return &SchedulerCreateSessionKeyParams{
		timeout: timeout,
	}
}

// NewSchedulerCreateSessionKeyParamsWithContext creates a new SchedulerCreateSessionKeyParams object
// with the ability to set a context for a request.
func NewSchedulerCreateSessionKeyParamsWithContext(ctx context.Context) *SchedulerCreateSessionKeyParams {
	return &SchedulerCreateSessionKeyParams{
		Context: ctx,
	}
}

// NewSchedulerCreateSessionKeyParamsWithHTTPClient creates a new SchedulerCreateSessionKeyParams object
// with the ability to set a custom HTTPClient for a request.
func NewSchedulerCreateSessionKeyParamsWithHTTPClient(client *http.Client) *SchedulerCreateSessionKeyParams {
	return &SchedulerCreateSessionKeyParams{
		HTTPClient: client,
	}
}

/* SchedulerCreateSessionKeyParams contains all the parameters to send to the API endpoint
   for the scheduler create session key operation.

   Typically these are written to a http.Request.
*/
type SchedulerCreateSessionKeyParams struct {

	// Body.
	Body *models.SchedulerSessionKeyRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the scheduler create session key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SchedulerCreateSessionKeyParams) WithDefaults() *SchedulerCreateSessionKeyParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the scheduler create session key params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SchedulerCreateSessionKeyParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the scheduler create session key params
func (o *SchedulerCreateSessionKeyParams) WithTimeout(timeout time.Duration) *SchedulerCreateSessionKeyParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the scheduler create session key params
func (o *SchedulerCreateSessionKeyParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the scheduler create session key params
func (o *SchedulerCreateSessionKeyParams) WithContext(ctx context.Context) *SchedulerCreateSessionKeyParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the scheduler create session key params
func (o *SchedulerCreateSessionKeyParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the scheduler create session key params
func (o *SchedulerCreateSessionKeyParams) WithHTTPClient(client *http.Client) *SchedulerCreateSessionKeyParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the scheduler create session key params
func (o *SchedulerCreateSessionKeyParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the scheduler create session key params
func (o *SchedulerCreateSessionKeyParams) WithBody(body *models.SchedulerSessionKeyRequest) *SchedulerCreateSessionKeyParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the scheduler create session key params
func (o *SchedulerCreateSessionKeyParams) SetBody(body *models.SchedulerSessionKeyRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SchedulerCreateSessionKeyParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
