// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/shillingio/scheduling.go/models"
)

// SchedulerRemoveProviderServiceReader is a Reader for the SchedulerRemoveProviderService structure.
type SchedulerRemoveProviderServiceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SchedulerRemoveProviderServiceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSchedulerRemoveProviderServiceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSchedulerRemoveProviderServiceDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSchedulerRemoveProviderServiceOK creates a SchedulerRemoveProviderServiceOK with default headers values
func NewSchedulerRemoveProviderServiceOK() *SchedulerRemoveProviderServiceOK {
	return &SchedulerRemoveProviderServiceOK{}
}

/* SchedulerRemoveProviderServiceOK describes a response with status code 200, with default header values.

A successful response.
*/
type SchedulerRemoveProviderServiceOK struct {
	Payload interface{}
}

func (o *SchedulerRemoveProviderServiceOK) Error() string {
	return fmt.Sprintf("[DELETE /v1/providers/{provider.id}/services/{service.id}][%d] schedulerRemoveProviderServiceOK  %+v", 200, o.Payload)
}
func (o *SchedulerRemoveProviderServiceOK) GetPayload() interface{} {
	return o.Payload
}

func (o *SchedulerRemoveProviderServiceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSchedulerRemoveProviderServiceDefault creates a SchedulerRemoveProviderServiceDefault with default headers values
func NewSchedulerRemoveProviderServiceDefault(code int) *SchedulerRemoveProviderServiceDefault {
	return &SchedulerRemoveProviderServiceDefault{
		_statusCode: code,
	}
}

/* SchedulerRemoveProviderServiceDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SchedulerRemoveProviderServiceDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the scheduler remove provider service default response
func (o *SchedulerRemoveProviderServiceDefault) Code() int {
	return o._statusCode
}

func (o *SchedulerRemoveProviderServiceDefault) Error() string {
	return fmt.Sprintf("[DELETE /v1/providers/{provider.id}/services/{service.id}][%d] Scheduler_RemoveProviderService default  %+v", o._statusCode, o.Payload)
}
func (o *SchedulerRemoveProviderServiceDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SchedulerRemoveProviderServiceDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
