// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/shillingio/scheduling.go/models"
)

// NewSchedulerCreateProviderParams creates a new SchedulerCreateProviderParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSchedulerCreateProviderParams() *SchedulerCreateProviderParams {
	return &SchedulerCreateProviderParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSchedulerCreateProviderParamsWithTimeout creates a new SchedulerCreateProviderParams object
// with the ability to set a timeout on a request.
func NewSchedulerCreateProviderParamsWithTimeout(timeout time.Duration) *SchedulerCreateProviderParams {
	return &SchedulerCreateProviderParams{
		timeout: timeout,
	}
}

// NewSchedulerCreateProviderParamsWithContext creates a new SchedulerCreateProviderParams object
// with the ability to set a context for a request.
func NewSchedulerCreateProviderParamsWithContext(ctx context.Context) *SchedulerCreateProviderParams {
	return &SchedulerCreateProviderParams{
		Context: ctx,
	}
}

// NewSchedulerCreateProviderParamsWithHTTPClient creates a new SchedulerCreateProviderParams object
// with the ability to set a custom HTTPClient for a request.
func NewSchedulerCreateProviderParamsWithHTTPClient(client *http.Client) *SchedulerCreateProviderParams {
	return &SchedulerCreateProviderParams{
		HTTPClient: client,
	}
}

/* SchedulerCreateProviderParams contains all the parameters to send to the API endpoint
   for the scheduler create provider operation.

   Typically these are written to a http.Request.
*/
type SchedulerCreateProviderParams struct {

	// Body.
	Body *models.SchedulingProvider

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the scheduler create provider params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SchedulerCreateProviderParams) WithDefaults() *SchedulerCreateProviderParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the scheduler create provider params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SchedulerCreateProviderParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the scheduler create provider params
func (o *SchedulerCreateProviderParams) WithTimeout(timeout time.Duration) *SchedulerCreateProviderParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the scheduler create provider params
func (o *SchedulerCreateProviderParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the scheduler create provider params
func (o *SchedulerCreateProviderParams) WithContext(ctx context.Context) *SchedulerCreateProviderParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the scheduler create provider params
func (o *SchedulerCreateProviderParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the scheduler create provider params
func (o *SchedulerCreateProviderParams) WithHTTPClient(client *http.Client) *SchedulerCreateProviderParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the scheduler create provider params
func (o *SchedulerCreateProviderParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the scheduler create provider params
func (o *SchedulerCreateProviderParams) WithBody(body *models.SchedulingProvider) *SchedulerCreateProviderParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the scheduler create provider params
func (o *SchedulerCreateProviderParams) SetBody(body *models.SchedulingProvider) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SchedulerCreateProviderParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
