// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"

	"github.com/shillingio/scheduling.go/models"
)

// NewSchedulerUpdateSessionParams creates a new SchedulerUpdateSessionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSchedulerUpdateSessionParams() *SchedulerUpdateSessionParams {
	return &SchedulerUpdateSessionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSchedulerUpdateSessionParamsWithTimeout creates a new SchedulerUpdateSessionParams object
// with the ability to set a timeout on a request.
func NewSchedulerUpdateSessionParamsWithTimeout(timeout time.Duration) *SchedulerUpdateSessionParams {
	return &SchedulerUpdateSessionParams{
		timeout: timeout,
	}
}

// NewSchedulerUpdateSessionParamsWithContext creates a new SchedulerUpdateSessionParams object
// with the ability to set a context for a request.
func NewSchedulerUpdateSessionParamsWithContext(ctx context.Context) *SchedulerUpdateSessionParams {
	return &SchedulerUpdateSessionParams{
		Context: ctx,
	}
}

// NewSchedulerUpdateSessionParamsWithHTTPClient creates a new SchedulerUpdateSessionParams object
// with the ability to set a custom HTTPClient for a request.
func NewSchedulerUpdateSessionParamsWithHTTPClient(client *http.Client) *SchedulerUpdateSessionParams {
	return &SchedulerUpdateSessionParams{
		HTTPClient: client,
	}
}

/* SchedulerUpdateSessionParams contains all the parameters to send to the API endpoint
   for the scheduler update session operation.

   Typically these are written to a http.Request.
*/
type SchedulerUpdateSessionParams struct {

	// Body.
	Body *models.SchedulerSessionRequest

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the scheduler update session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SchedulerUpdateSessionParams) WithDefaults() *SchedulerUpdateSessionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the scheduler update session params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SchedulerUpdateSessionParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the scheduler update session params
func (o *SchedulerUpdateSessionParams) WithTimeout(timeout time.Duration) *SchedulerUpdateSessionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the scheduler update session params
func (o *SchedulerUpdateSessionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the scheduler update session params
func (o *SchedulerUpdateSessionParams) WithContext(ctx context.Context) *SchedulerUpdateSessionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the scheduler update session params
func (o *SchedulerUpdateSessionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the scheduler update session params
func (o *SchedulerUpdateSessionParams) WithHTTPClient(client *http.Client) *SchedulerUpdateSessionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the scheduler update session params
func (o *SchedulerUpdateSessionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithBody adds the body to the scheduler update session params
func (o *SchedulerUpdateSessionParams) WithBody(body *models.SchedulerSessionRequest) *SchedulerUpdateSessionParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the scheduler update session params
func (o *SchedulerUpdateSessionParams) SetBody(body *models.SchedulerSessionRequest) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SchedulerUpdateSessionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error
	if o.Body != nil {
		if err := r.SetBodyParam(o.Body); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
