// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/shillingio/scheduling.go/models"
)

// SchedulerSearchProvidersReader is a Reader for the SchedulerSearchProviders structure.
type SchedulerSearchProvidersReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SchedulerSearchProvidersReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSchedulerSearchProvidersOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSchedulerSearchProvidersDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSchedulerSearchProvidersOK creates a SchedulerSearchProvidersOK with default headers values
func NewSchedulerSearchProvidersOK() *SchedulerSearchProvidersOK {
	return &SchedulerSearchProvidersOK{}
}

/* SchedulerSearchProvidersOK describes a response with status code 200, with default header values.

A successful response.
*/
type SchedulerSearchProvidersOK struct {
	Payload *models.SchedulerProviderResponse
}

func (o *SchedulerSearchProvidersOK) Error() string {
	return fmt.Sprintf("[POST /v1/search/providers][%d] schedulerSearchProvidersOK  %+v", 200, o.Payload)
}
func (o *SchedulerSearchProvidersOK) GetPayload() *models.SchedulerProviderResponse {
	return o.Payload
}

func (o *SchedulerSearchProvidersOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SchedulerProviderResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSchedulerSearchProvidersDefault creates a SchedulerSearchProvidersDefault with default headers values
func NewSchedulerSearchProvidersDefault(code int) *SchedulerSearchProvidersDefault {
	return &SchedulerSearchProvidersDefault{
		_statusCode: code,
	}
}

/* SchedulerSearchProvidersDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SchedulerSearchProvidersDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the scheduler search providers default response
func (o *SchedulerSearchProvidersDefault) Code() int {
	return o._statusCode
}

func (o *SchedulerSearchProvidersDefault) Error() string {
	return fmt.Sprintf("[POST /v1/search/providers][%d] Scheduler_SearchProviders default  %+v", o._statusCode, o.Payload)
}
func (o *SchedulerSearchProvidersDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SchedulerSearchProvidersDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
