// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/shillingio/scheduling.go/models"
)

// SchedulerCreateSessionReader is a Reader for the SchedulerCreateSession structure.
type SchedulerCreateSessionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SchedulerCreateSessionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSchedulerCreateSessionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSchedulerCreateSessionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSchedulerCreateSessionOK creates a SchedulerCreateSessionOK with default headers values
func NewSchedulerCreateSessionOK() *SchedulerCreateSessionOK {
	return &SchedulerCreateSessionOK{}
}

/* SchedulerCreateSessionOK describes a response with status code 200, with default header values.

A successful response.
*/
type SchedulerCreateSessionOK struct {
	Payload *models.SchedulerSessionResponse
}

func (o *SchedulerCreateSessionOK) Error() string {
	return fmt.Sprintf("[POST /v1/sessions][%d] schedulerCreateSessionOK  %+v", 200, o.Payload)
}
func (o *SchedulerCreateSessionOK) GetPayload() *models.SchedulerSessionResponse {
	return o.Payload
}

func (o *SchedulerCreateSessionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SchedulerSessionResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSchedulerCreateSessionDefault creates a SchedulerCreateSessionDefault with default headers values
func NewSchedulerCreateSessionDefault(code int) *SchedulerCreateSessionDefault {
	return &SchedulerCreateSessionDefault{
		_statusCode: code,
	}
}

/* SchedulerCreateSessionDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SchedulerCreateSessionDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the scheduler create session default response
func (o *SchedulerCreateSessionDefault) Code() int {
	return o._statusCode
}

func (o *SchedulerCreateSessionDefault) Error() string {
	return fmt.Sprintf("[POST /v1/sessions][%d] Scheduler_CreateSession default  %+v", o._statusCode, o.Payload)
}
func (o *SchedulerCreateSessionDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SchedulerCreateSessionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
