// Code generated by go-swagger; DO NOT EDIT.

package scheduler

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/shillingio/scheduling.go/models"
)

// SchedulerCreateProviderReader is a Reader for the SchedulerCreateProvider structure.
type SchedulerCreateProviderReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SchedulerCreateProviderReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSchedulerCreateProviderOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSchedulerCreateProviderDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSchedulerCreateProviderOK creates a SchedulerCreateProviderOK with default headers values
func NewSchedulerCreateProviderOK() *SchedulerCreateProviderOK {
	return &SchedulerCreateProviderOK{}
}

/* SchedulerCreateProviderOK describes a response with status code 200, with default header values.

A successful response.
*/
type SchedulerCreateProviderOK struct {
	Payload *models.SchedulerProviderResponse
}

func (o *SchedulerCreateProviderOK) Error() string {
	return fmt.Sprintf("[POST /v1/providers][%d] schedulerCreateProviderOK  %+v", 200, o.Payload)
}
func (o *SchedulerCreateProviderOK) GetPayload() *models.SchedulerProviderResponse {
	return o.Payload
}

func (o *SchedulerCreateProviderOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SchedulerProviderResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSchedulerCreateProviderDefault creates a SchedulerCreateProviderDefault with default headers values
func NewSchedulerCreateProviderDefault(code int) *SchedulerCreateProviderDefault {
	return &SchedulerCreateProviderDefault{
		_statusCode: code,
	}
}

/* SchedulerCreateProviderDefault describes a response with status code -1, with default header values.

An unexpected error response.
*/
type SchedulerCreateProviderDefault struct {
	_statusCode int

	Payload *models.RPCStatus
}

// Code gets the status code for the scheduler create provider default response
func (o *SchedulerCreateProviderDefault) Code() int {
	return o._statusCode
}

func (o *SchedulerCreateProviderDefault) Error() string {
	return fmt.Sprintf("[POST /v1/providers][%d] Scheduler_CreateProvider default  %+v", o._statusCode, o.Payload)
}
func (o *SchedulerCreateProviderDefault) GetPayload() *models.RPCStatus {
	return o.Payload
}

func (o *SchedulerCreateProviderDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RPCStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
