// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SchedulingLocation scheduling location
//
// swagger:model schedulingLocation
type SchedulingLocation struct {

	// Specific latitude point to use
	Latitude float32 `json:"latitude,omitempty"`

	// Specific longitude point to use
	Longitude float32 `json:"longitude,omitempty"`

	// Address query (ex: 123 Main St., San Diego, CA, 92101, San Diego, CA, etc.)
	Query string `json:"query,omitempty"`

	// Zip code
	Zip string `json:"zip,omitempty"`
}

// Validate validates this scheduling location
func (m *SchedulingLocation) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this scheduling location based on context it is used
func (m *SchedulingLocation) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SchedulingLocation) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SchedulingLocation) UnmarshalBinary(b []byte) error {
	var res SchedulingLocation
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
