// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SchedulerStatsRequest scheduler stats request
//
// swagger:model schedulerStatsRequest
type SchedulerStatsRequest struct {

	// organization id
	OrganizationID string `json:"organization_id,omitempty"`

	// organization ids
	OrganizationIds []string `json:"organization_ids"`
}

// Validate validates this scheduler stats request
func (m *SchedulerStatsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this scheduler stats request based on context it is used
func (m *SchedulerStatsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SchedulerStatsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SchedulerStatsRequest) UnmarshalBinary(b []byte) error {
	var res SchedulerStatsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
