// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SchedulingServiceConfig scheduling service config
//
// swagger:model schedulingServiceConfig
type SchedulingServiceConfig struct {

	// durations
	Durations []int32 `json:"durations"`

	// fixed duration
	FixedDuration int32 `json:"fixed_duration,omitempty"`
}

// Validate validates this scheduling service config
func (m *SchedulingServiceConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this scheduling service config based on context it is used
func (m *SchedulingServiceConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SchedulingServiceConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SchedulingServiceConfig) UnmarshalBinary(b []byte) error {
	var res SchedulingServiceConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
