// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SchedulerAvailabilityResponse scheduler availability response
//
// swagger:model schedulerAvailabilityResponse
type SchedulerAvailabilityResponse struct {

	// available
	Available []*SchedulingAppointmentSlot `json:"available"`

	// limit
	Limit int32 `json:"limit,omitempty"`

	// offset
	Offset int32 `json:"offset,omitempty"`

	// total
	Total int32 `json:"total,omitempty"`
}

// Validate validates this scheduler availability response
func (m *SchedulerAvailabilityResponse) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAvailable(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SchedulerAvailabilityResponse) validateAvailable(formats strfmt.Registry) error {
	if swag.IsZero(m.Available) { // not required
		return nil
	}

	for i := 0; i < len(m.Available); i++ {
		if swag.IsZero(m.Available[i]) { // not required
			continue
		}

		if m.Available[i] != nil {
			if err := m.Available[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("available" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("available" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this scheduler availability response based on the context it is used
func (m *SchedulerAvailabilityResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAvailable(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *SchedulerAvailabilityResponse) contextValidateAvailable(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Available); i++ {

		if m.Available[i] != nil {
			if err := m.Available[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("available" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("available" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *SchedulerAvailabilityResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SchedulerAvailabilityResponse) UnmarshalBinary(b []byte) error {
	var res SchedulerAvailabilityResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
