// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SchedulingZipcode scheduling zipcode
//
// swagger:model schedulingZipcode
type SchedulingZipcode struct {

	// city
	City string `json:"city,omitempty"`

	// country
	Country string `json:"country,omitempty"`

	// dst
	Dst bool `json:"dst,omitempty"`

	// latitude
	Latitude float32 `json:"latitude,omitempty"`

	// longitude
	Longitude float32 `json:"longitude,omitempty"`

	// state
	State string `json:"state,omitempty"`

	// timezone
	Timezone int32 `json:"timezone,omitempty"`

	// zip
	Zip string `json:"zip,omitempty"`
}

// Validate validates this scheduling zipcode
func (m *SchedulingZipcode) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this scheduling zipcode based on context it is used
func (m *SchedulingZipcode) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SchedulingZipcode) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SchedulingZipcode) UnmarshalBinary(b []byte) error {
	var res SchedulingZipcode
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
